# DO NOT EDIT THIS FILE!
#
# Python module CORBA_IDL generated by omniidl

import omniORB
omniORB.updateModule("CORBA_IDL")

# ** 1. Stub files contributing to this module
import GameActions_idl

# ** 2. Sub-modules

# ** 3. End
