package CORBA_IDL;


/**
* CORBA_IDL/charListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

abstract public class charListHelper
{
  private static String  _id = "IDL:CORBA_IDL/charList:1.0";

  public static void insert (org.omg.CORBA.Any a, char[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static char[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_char);
      __typeCode = org.omg.CORBA.ORB.init ().create_array_tc (17, __typeCode );
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (CORBA_IDL.charListHelper.id (), "charList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static char[] read (org.omg.CORBA.portable.InputStream istream)
  {
    char value[] = null;
    value = new char[17];
    for (int _o0 = 0;_o0 < (17); ++_o0)
    {
      value[_o0] = istream.read_char ();
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, char[] value)
  {
    if (value.length != (17))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (17); ++_i0)
    {
      ostream.write_char (value[_i0]);
    }
  }

}
