package CORBA_IDL;

/**
* CORBA_IDL/GameActionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class GameActionsHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA_IDL.GameActions value = null;

  public GameActionsHolder ()
  {
  }

  public GameActionsHolder (CORBA_IDL.GameActions initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA_IDL.GameActionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA_IDL.GameActionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA_IDL.GameActionsHelper.type ();
  }

}
