package CORBA_IDL;


/**
* CORBA_IDL/GameActionsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

abstract public class GameActionsHelper
{
  private static String  _id = "IDL:CORBA_IDL/GameActions:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBA_IDL.GameActions that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBA_IDL.GameActions extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CORBA_IDL.GameActionsHelper.id (), "GameActions");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBA_IDL.GameActions read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameActionsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBA_IDL.GameActions value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CORBA_IDL.GameActions narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBA_IDL.GameActions)
      return (CORBA_IDL.GameActions)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CORBA_IDL._GameActionsStub stub = new CORBA_IDL._GameActionsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CORBA_IDL.GameActions unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBA_IDL.GameActions)
      return (CORBA_IDL.GameActions)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CORBA_IDL._GameActionsStub stub = new CORBA_IDL._GameActionsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
