package CORBA_IDL;


/**
* CORBA_IDL/InvalidWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class InvalidWordException extends org.omg.CORBA.UserException
{

  public InvalidWordException ()
  {
    super(InvalidWordExceptionHelper.id());
  } // ctor


  public InvalidWordException (String $reason)
  {
    super(InvalidWordExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidWordException
