package CORBA_IDL;


/**
* CORBA_IDL/leaderboardListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class leaderboardListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[][] = null;

  public leaderboardListHolder ()
  {
  }

  public leaderboardListHolder (String[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA_IDL.leaderboardListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA_IDL.leaderboardListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA_IDL.leaderboardListHelper.type ();
  }

}
