package CORBA_IDL;


/**
* CORBA_IDL/NoWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class NoWordException extends org.omg.CORBA.UserException
{

  public NoWordException ()
  {
    super(NoWordExceptionHelper.id());
  } // ctor


  public NoWordException (String $reason)
  {
    super(NoWordExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoWordException
