package CORBA_IDL;


/**
* CORBA_IDL/ShortWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class ShortWordException extends org.omg.CORBA.UserException
{

  public ShortWordException ()
  {
    super(ShortWordExceptionHelper.id());
  } // ctor


  public ShortWordException (String $reason)
  {
    super(ShortWordExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ShortWordException
