package CORBA_IDL;

/**
* CORBA_IDL/ShortWordExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class ShortWordExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBA_IDL.ShortWordException value = null;

  public ShortWordExceptionHolder ()
  {
  }

  public ShortWordExceptionHolder (CORBA_IDL.ShortWordException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBA_IDL.ShortWordExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBA_IDL.ShortWordExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBA_IDL.ShortWordExceptionHelper.type ();
  }

}
