package CORBA_IDL;


/**
* CORBA_IDL/UserNotFoundExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

abstract public class UserNotFoundExceptionHelper
{
  private static String  _id = "IDL:CORBA_IDL/UserNotFoundException:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBA_IDL.UserNotFoundException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBA_IDL.UserNotFoundException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (CORBA_IDL.UserNotFoundExceptionHelper.id (), "UserNotFoundException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBA_IDL.UserNotFoundException read (org.omg.CORBA.portable.InputStream istream)
  {
    CORBA_IDL.UserNotFoundException value = new CORBA_IDL.UserNotFoundException ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBA_IDL.UserNotFoundException value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
