package CORBA_IDL;


/**
* CORBA_IDL/UserNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class UserNotFoundException extends org.omg.CORBA.UserException
{

  public UserNotFoundException ()
  {
    super(UserNotFoundExceptionHelper.id());
  } // ctor


  public UserNotFoundException (String $reason)
  {
    super(UserNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class UserNotFoundException
