package CORBA_IDL;


/**
* CORBA_IDL/WordRepeatedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameActions.idl
* Tuesday, May 9, 2023 9:47:20 AM CST
*/

public final class WordRepeatedException extends org.omg.CORBA.UserException
{

  public WordRepeatedException ()
  {
    super(WordRepeatedExceptionHelper.id());
  } // ctor


  public WordRepeatedException (String $reason)
  {
    super(WordRepeatedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class WordRepeatedException
