# Python stubs generated by omniidl from GameActions.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "CORBA_IDL"
#
__name__ = "CORBA_IDL"
_0_CORBA_IDL = omniORB.openModule("CORBA_IDL", r"GameActions.idl")
_0_CORBA_IDL__POA = omniORB.openModule("CORBA_IDL__POA", r"GameActions.idl")


# exception NoWordException
_0_CORBA_IDL.NoWordException = omniORB.newEmptyClass()
class NoWordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/NoWordException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.NoWordException = NoWordException
_0_CORBA_IDL._d_NoWordException  = (omniORB.tcInternal.tv_except, NoWordException, NoWordException._NP_RepositoryId, "NoWordException")
_0_CORBA_IDL._tc_NoWordException = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_NoWordException)
omniORB.registerType(NoWordException._NP_RepositoryId, _0_CORBA_IDL._d_NoWordException, _0_CORBA_IDL._tc_NoWordException)
del NoWordException

# exception ShortWordException
_0_CORBA_IDL.ShortWordException = omniORB.newEmptyClass()
class ShortWordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/ShortWordException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.ShortWordException = ShortWordException
_0_CORBA_IDL._d_ShortWordException  = (omniORB.tcInternal.tv_except, ShortWordException, ShortWordException._NP_RepositoryId, "ShortWordException")
_0_CORBA_IDL._tc_ShortWordException = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_ShortWordException)
omniORB.registerType(ShortWordException._NP_RepositoryId, _0_CORBA_IDL._d_ShortWordException, _0_CORBA_IDL._tc_ShortWordException)
del ShortWordException

# exception WordRepeatedException
_0_CORBA_IDL.WordRepeatedException = omniORB.newEmptyClass()
class WordRepeatedException (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/WordRepeatedException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.WordRepeatedException = WordRepeatedException
_0_CORBA_IDL._d_WordRepeatedException  = (omniORB.tcInternal.tv_except, WordRepeatedException, WordRepeatedException._NP_RepositoryId, "WordRepeatedException")
_0_CORBA_IDL._tc_WordRepeatedException = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_WordRepeatedException)
omniORB.registerType(WordRepeatedException._NP_RepositoryId, _0_CORBA_IDL._d_WordRepeatedException, _0_CORBA_IDL._tc_WordRepeatedException)
del WordRepeatedException

# exception InvalidWordException
_0_CORBA_IDL.InvalidWordException = omniORB.newEmptyClass()
class InvalidWordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/InvalidWordException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.InvalidWordException = InvalidWordException
_0_CORBA_IDL._d_InvalidWordException  = (omniORB.tcInternal.tv_except, InvalidWordException, InvalidWordException._NP_RepositoryId, "InvalidWordException")
_0_CORBA_IDL._tc_InvalidWordException = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_InvalidWordException)
omniORB.registerType(InvalidWordException._NP_RepositoryId, _0_CORBA_IDL._d_InvalidWordException, _0_CORBA_IDL._tc_InvalidWordException)
del InvalidWordException

# exception UserNotFoundException
_0_CORBA_IDL.UserNotFoundException = omniORB.newEmptyClass()
class UserNotFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/UserNotFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.UserNotFoundException = UserNotFoundException
_0_CORBA_IDL._d_UserNotFoundException  = (omniORB.tcInternal.tv_except, UserNotFoundException, UserNotFoundException._NP_RepositoryId, "UserNotFoundException")
_0_CORBA_IDL._tc_UserNotFoundException = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_UserNotFoundException)
omniORB.registerType(UserNotFoundException._NP_RepositoryId, _0_CORBA_IDL._d_UserNotFoundException, _0_CORBA_IDL._tc_UserNotFoundException)
del UserNotFoundException

# exception WrongCredentials
_0_CORBA_IDL.WrongCredentials = omniORB.newEmptyClass()
class WrongCredentials (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/WrongCredentials:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.WrongCredentials = WrongCredentials
_0_CORBA_IDL._d_WrongCredentials  = (omniORB.tcInternal.tv_except, WrongCredentials, WrongCredentials._NP_RepositoryId, "WrongCredentials")
_0_CORBA_IDL._tc_WrongCredentials = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_WrongCredentials)
omniORB.registerType(WrongCredentials._NP_RepositoryId, _0_CORBA_IDL._d_WrongCredentials, _0_CORBA_IDL._tc_WrongCredentials)
del WrongCredentials

# exception UserOnlineException
_0_CORBA_IDL.UserOnlineException = omniORB.newEmptyClass()
class UserOnlineException (CORBA.UserException):
    _NP_RepositoryId = "IDL:CORBA_IDL/UserOnlineException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_CORBA_IDL.UserOnlineException = UserOnlineException
_0_CORBA_IDL._d_UserOnlineException  = (omniORB.tcInternal.tv_except, UserOnlineException, UserOnlineException._NP_RepositoryId, "UserOnlineException")
_0_CORBA_IDL._tc_UserOnlineException = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_UserOnlineException)
omniORB.registerType(UserOnlineException._NP_RepositoryId, _0_CORBA_IDL._d_UserOnlineException, _0_CORBA_IDL._tc_UserOnlineException)
del UserOnlineException

# typedef ... leaderboardList
class leaderboardList:
    _NP_RepositoryId = "IDL:CORBA_IDL/leaderboardList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_CORBA_IDL.leaderboardList = leaderboardList
_0_CORBA_IDL._d_leaderboardList  = (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 2), 5)
_0_CORBA_IDL._ad_leaderboardList = (omniORB.tcInternal.tv_alias, leaderboardList._NP_RepositoryId, "leaderboardList", (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_array, (omniORB.tcInternal.tv_string,0), 2), 5))
_0_CORBA_IDL._tc_leaderboardList = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._ad_leaderboardList)
omniORB.registerType(leaderboardList._NP_RepositoryId, _0_CORBA_IDL._ad_leaderboardList, _0_CORBA_IDL._tc_leaderboardList)
del leaderboardList

# typedef ... charList
class charList:
    _NP_RepositoryId = "IDL:CORBA_IDL/charList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_CORBA_IDL.charList = charList
_0_CORBA_IDL._d_charList  = (omniORB.tcInternal.tv_array, omniORB.tcInternal.tv_char, 17)
_0_CORBA_IDL._ad_charList = (omniORB.tcInternal.tv_alias, charList._NP_RepositoryId, "charList", (omniORB.tcInternal.tv_array, omniORB.tcInternal.tv_char, 17))
_0_CORBA_IDL._tc_charList = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._ad_charList)
omniORB.registerType(charList._NP_RepositoryId, _0_CORBA_IDL._ad_charList, _0_CORBA_IDL._tc_charList)
del charList

# typedef ... words
class words:
    _NP_RepositoryId = "IDL:CORBA_IDL/words:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_CORBA_IDL.words = words
_0_CORBA_IDL._d_words  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_CORBA_IDL._ad_words = (omniORB.tcInternal.tv_alias, words._NP_RepositoryId, "words", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_CORBA_IDL._tc_words = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._ad_words)
omniORB.registerType(words._NP_RepositoryId, _0_CORBA_IDL._ad_words, _0_CORBA_IDL._tc_words)
del words

# interface GameActions
_0_CORBA_IDL._d_GameActions = (omniORB.tcInternal.tv_objref, "IDL:CORBA_IDL/GameActions:1.0", "GameActions")
omniORB.typeMapping["IDL:CORBA_IDL/GameActions:1.0"] = _0_CORBA_IDL._d_GameActions
_0_CORBA_IDL.GameActions = omniORB.newEmptyClass()
class GameActions :
    _NP_RepositoryId = _0_CORBA_IDL._d_GameActions[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_CORBA_IDL.GameActions = GameActions
_0_CORBA_IDL._tc_GameActions = omniORB.tcInternal.createTypeCode(_0_CORBA_IDL._d_GameActions)
omniORB.registerType(GameActions._NP_RepositoryId, _0_CORBA_IDL._d_GameActions, _0_CORBA_IDL._tc_GameActions)

# GameActions operations and attributes
GameActions._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_CORBA_IDL.UserNotFoundException._NP_RepositoryId: _0_CORBA_IDL._d_UserNotFoundException, _0_CORBA_IDL.WrongCredentials._NP_RepositoryId: _0_CORBA_IDL._d_WrongCredentials, _0_CORBA_IDL.UserOnlineException._NP_RepositoryId: _0_CORBA_IDL._d_UserOnlineException})
GameActions._d_joinGame = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
GameActions._d_getTimer = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
GameActions._d_getGamePlayers = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:CORBA_IDL/words:1.0"], ), None)
GameActions._d_initializeGame = ((omniORB.tcInternal.tv_long, ), (), None)
GameActions._d_runGame = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_boolean, ), None)
GameActions._d_sendWord = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_CORBA_IDL.NoWordException._NP_RepositoryId: _0_CORBA_IDL._d_NoWordException, _0_CORBA_IDL.ShortWordException._NP_RepositoryId: _0_CORBA_IDL._d_ShortWordException, _0_CORBA_IDL.WordRepeatedException._NP_RepositoryId: _0_CORBA_IDL._d_WordRepeatedException, _0_CORBA_IDL.InvalidWordException._NP_RepositoryId: _0_CORBA_IDL._d_InvalidWordException})
GameActions._d_getCharacters = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:CORBA_IDL/charList:1.0"], ), None)
GameActions._d_getEnteredWords = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:CORBA_IDL/words:1.0"], ), None)
GameActions._d_getRoundWinner = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
GameActions._d_getGameWinner = ((omniORB.tcInternal.tv_long, ), ((omniORB.tcInternal.tv_string,0), ), None)
GameActions._d_getNoWinInGame = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), None)
GameActions._d_getLeaderboardWinList = ((), (omniORB.typeMapping["IDL:CORBA_IDL/leaderboardList:1.0"], ), None)
GameActions._d_getLeaderBoardLongestWordsList = ((), (omniORB.typeMapping["IDL:CORBA_IDL/leaderboardList:1.0"], ), None)
GameActions._d_quitGame = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), None)
GameActions._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)

# GameActions object reference
class _objref_GameActions (CORBA.Object):
    _NP_RepositoryId = GameActions._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_CORBA_IDL.GameActions._d_login, args)

    def joinGame(self, *args):
        return self._obj.invoke("joinGame", _0_CORBA_IDL.GameActions._d_joinGame, args)

    def getTimer(self, *args):
        return self._obj.invoke("getTimer", _0_CORBA_IDL.GameActions._d_getTimer, args)

    def getGamePlayers(self, *args):
        return self._obj.invoke("getGamePlayers", _0_CORBA_IDL.GameActions._d_getGamePlayers, args)

    def initializeGame(self, *args):
        return self._obj.invoke("initializeGame", _0_CORBA_IDL.GameActions._d_initializeGame, args)

    def runGame(self, *args):
        return self._obj.invoke("runGame", _0_CORBA_IDL.GameActions._d_runGame, args)

    def sendWord(self, *args):
        return self._obj.invoke("sendWord", _0_CORBA_IDL.GameActions._d_sendWord, args)

    def getCharacters(self, *args):
        return self._obj.invoke("getCharacters", _0_CORBA_IDL.GameActions._d_getCharacters, args)

    def getEnteredWords(self, *args):
        return self._obj.invoke("getEnteredWords", _0_CORBA_IDL.GameActions._d_getEnteredWords, args)

    def getRoundWinner(self, *args):
        return self._obj.invoke("getRoundWinner", _0_CORBA_IDL.GameActions._d_getRoundWinner, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_CORBA_IDL.GameActions._d_getGameWinner, args)

    def getNoWinInGame(self, *args):
        return self._obj.invoke("getNoWinInGame", _0_CORBA_IDL.GameActions._d_getNoWinInGame, args)

    def getLeaderboardWinList(self, *args):
        return self._obj.invoke("getLeaderboardWinList", _0_CORBA_IDL.GameActions._d_getLeaderboardWinList, args)

    def getLeaderBoardLongestWordsList(self, *args):
        return self._obj.invoke("getLeaderBoardLongestWordsList", _0_CORBA_IDL.GameActions._d_getLeaderBoardLongestWordsList, args)

    def quitGame(self, *args):
        return self._obj.invoke("quitGame", _0_CORBA_IDL.GameActions._d_quitGame, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_CORBA_IDL.GameActions._d_logout, args)

omniORB.registerObjref(GameActions._NP_RepositoryId, _objref_GameActions)
_0_CORBA_IDL._objref_GameActions = _objref_GameActions
del GameActions, _objref_GameActions

# GameActions skeleton
__name__ = "CORBA_IDL__POA"
class GameActions (PortableServer.Servant):
    _NP_RepositoryId = _0_CORBA_IDL.GameActions._NP_RepositoryId


    _omni_op_d = {"login": _0_CORBA_IDL.GameActions._d_login, "joinGame": _0_CORBA_IDL.GameActions._d_joinGame, "getTimer": _0_CORBA_IDL.GameActions._d_getTimer, "getGamePlayers": _0_CORBA_IDL.GameActions._d_getGamePlayers, "initializeGame": _0_CORBA_IDL.GameActions._d_initializeGame, "runGame": _0_CORBA_IDL.GameActions._d_runGame, "sendWord": _0_CORBA_IDL.GameActions._d_sendWord, "getCharacters": _0_CORBA_IDL.GameActions._d_getCharacters, "getEnteredWords": _0_CORBA_IDL.GameActions._d_getEnteredWords, "getRoundWinner": _0_CORBA_IDL.GameActions._d_getRoundWinner, "getGameWinner": _0_CORBA_IDL.GameActions._d_getGameWinner, "getNoWinInGame": _0_CORBA_IDL.GameActions._d_getNoWinInGame, "getLeaderboardWinList": _0_CORBA_IDL.GameActions._d_getLeaderboardWinList, "getLeaderBoardLongestWordsList": _0_CORBA_IDL.GameActions._d_getLeaderBoardLongestWordsList, "quitGame": _0_CORBA_IDL.GameActions._d_quitGame, "logout": _0_CORBA_IDL.GameActions._d_logout}

GameActions._omni_skeleton = GameActions
_0_CORBA_IDL__POA.GameActions = GameActions
omniORB.registerSkeleton(GameActions._NP_RepositoryId, GameActions)
del GameActions
__name__ = "CORBA_IDL"

#
# End of module "CORBA_IDL"
#
__name__ = "GameActions_idl"

_exported_modules = ( "CORBA_IDL", )

# The end.
